process.env.DEFAULT_IDENTITY_NAME = 'STATION';
process.env.DEFAULT_CENTRAL_SYSTEM_URL = 'ws://localhost:20001';
process.env.WAIT_FOR_MESSAGE_CHECK_INTERVAL_IN_MS = '500';
process.env.WAIT_FOR_MESSAGE_CHECK_MAX_ATTEMPTS = '40';
